package com.flyingh.ws.server;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.0.1
 * 2014-09-13T13:49:00.834+08:00
 * Generated source version: 3.0.1
 * 
 */
@WebService(targetNamespace = "http://server.ws.flyingh.com/", name = "HelloWorldService")
@XmlSeeAlso({ObjectFactory.class})
public interface HelloWorldService {

    @WebMethod
    @Action(input = "http://server.ws.flyingh.com/HelloWorldService/getBooksByUserRequest", output = "http://server.ws.flyingh.com/HelloWorldService/getBooksByUserResponse")
    @RequestWrapper(localName = "getBooksByUser", targetNamespace = "http://server.ws.flyingh.com/", className = "com.flyingh.ws.server.GetBooksByUser")
    @ResponseWrapper(localName = "getBooksByUserResponse", targetNamespace = "http://server.ws.flyingh.com/", className = "com.flyingh.ws.server.GetBooksByUserResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.util.List<com.flyingh.ws.server.Book> getBooksByUser(
        @WebParam(name = "arg0", targetNamespace = "")
        com.flyingh.ws.server.User arg0
    );

    @WebMethod
    @Action(input = "http://server.ws.flyingh.com/HelloWorldService/getAllBooksRequest", output = "http://server.ws.flyingh.com/HelloWorldService/getAllBooksResponse")
    @RequestWrapper(localName = "getAllBooks", targetNamespace = "http://server.ws.flyingh.com/", className = "com.flyingh.ws.server.GetAllBooks")
    @ResponseWrapper(localName = "getAllBooksResponse", targetNamespace = "http://server.ws.flyingh.com/", className = "com.flyingh.ws.server.GetAllBooksResponse")
    @WebResult(name = "return", targetNamespace = "")
    public com.flyingh.ws.server.Books getAllBooks();

    @WebMethod
    @Action(input = "http://server.ws.flyingh.com/HelloWorldService/sayRequest", output = "http://server.ws.flyingh.com/HelloWorldService/sayResponse")
    @RequestWrapper(localName = "say", targetNamespace = "http://server.ws.flyingh.com/", className = "com.flyingh.ws.server.Say")
    @ResponseWrapper(localName = "sayResponse", targetNamespace = "http://server.ws.flyingh.com/", className = "com.flyingh.ws.server.SayResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.lang.String say(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0
    );
}
